<?php

namespace AppBundle\Repository;

/**
 * LogosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogosRepository extends \Doctrine\ORM\EntityRepository
{
}
